name: Debounce Workflow

on:
  push:
    branches: [ "sprint-2" ]
  pull_request:
    branches: [ "sprint-2" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./debounce

      - name: Build the project
        run: npm run build
        working-directory: ./debounce

